import type { Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";
import { theSeasons, helloParisSerif } from "./fonts";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${theSeasons.variable} ${helloParisSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
